In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [4]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369


In [6]:
df['fuel_type'].nunique()

2

In [8]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [11]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max().round(2)

np.float64(23.76)

In [13]:
median_horsepower = df['horsepower'].median()
median_horsepower

np.float64(149.0)

In [19]:
mode_horsepower = df['horsepower'].mode()[0]

In [21]:
updated_horsepower = df['horsepower'].fillna(mode_horsepower)
updated_horsepower.median()

np.float64(152.0)

In [23]:
cars_from_Asia = df[df.origin == 'Asia']

In [27]:
X = cars_from_Asia[['vehicle_weight', 'model_year']].head(7).to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [29]:
transpose_X = X.T
transpose_X

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [32]:
XTX = X.dot(transpose_X)
XTX.round(2)

array([[11431242.46, 11608190.93, 13770311.23, 10111792.75, 11282536.2 ,
        11780081.29, 14281180.86],
       [11608190.93, 11790026.47, 14007802.21, 10255171.44, 11455668.7 ,
        11966096.79, 14531088.48],
       [13770311.23, 14007802.21, 16863697.77, 12031947.84, 13574023.46,
        14232076.06, 17530181.52],
       [10111792.75, 10255171.44, 12031947.84,  9025088.58,  9989516.76,
        10397924.17, 12456257.92],
       [11282536.2 , 11455668.7 , 13574023.46,  9989516.76, 11136831.64,
        11624252.16, 14075069.26],
       [11780081.29, 11966096.79, 14232076.06, 10397924.17, 11624252.16,
        12145826.26, 14766233.03],
       [14281180.86, 14531088.48, 17530181.52, 12456257.92, 14075069.26,
        14766233.03, 18228960.14]])

In [36]:
XTX_inv = np.linalg.inv(XTX)

In [34]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [40]:
transpose_X.dot(XTX_inv).dot(y).sum()

np.float64(-0.4912989164442476)