In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [9]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
a[2]

np.int64(3)

In [11]:
a[2] = 10

In [12]:
a[2]

np.int64(10)

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(10, 100, 4)

array([ 10.,  40.,  70., 100.])

In [23]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
n[0, 1] = 20

In [29]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [30]:
n[0]

array([ 1, 20,  3])

In [31]:
n[2] = [1,1,1]

In [32]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [37]:
n[:, 2] = [0,1,2]

In [38]:
n[:,2]

array([0, 1, 2])

In [39]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [42]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [44]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [45]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [46]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [51]:
10 + (a * 2)

array([10, 12, 14, 16, 18])

In [56]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [57]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [58]:
a >= 2

array([False, False,  True,  True,  True])

In [59]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [60]:
a > b

array([False, False,  True,  True,  True])

In [63]:
a[a > b]

array([2, 3, 4])

In [64]:
a

array([0, 1, 2, 3, 4])

In [65]:
a.min()

np.int64(0)

In [66]:
a.max()

np.int64(4)

In [67]:
a.sum()

np.int64(10)

In [68]:
a.mean()

np.float64(2.0)

In [69]:
a.std()

np.float64(1.4142135623730951)